version: "3"
services:
  client:
    platform: linux/amd64
    build:
      context: "."
      dockerfile: raydevs.Dockerfile
    ports:
      - "3000:3000"
    image: ghcr.io/raygamedev/raydevs:latest
    command: /app/server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
